// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphqlmodel

type Appointment struct {
	ID          string    `json:"id"`
	Description string    `json:"description"`
	Time        *DateTime `json:"time"`
	User        *User     `json:"user"`
}

type DateTime struct {
	Date  string `json:"date"`
	Start string `json:"start"`
	End   string `json:"end"`
}

type DateTimeInput struct {
	Date  string `json:"date"`
	Start string `json:"start"`
	End   string `json:"end"`
}

type NewAppointment struct {
	Description string         `json:"description"`
	Time        *DateTimeInput `json:"time"`
	User        *UserInput     `json:"user"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type UserInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}
